## Chapter 11 - Sorting Arrays

In [1]:
import numpy as np

### Fast Sorting in NumPy: `np.sort` and `np.argsort`

- The `np.sort` function is analogous to Python’s built-in sorted function, and will efficiently return a sorted copy of an array:

In [9]:
x = np.array([2, 1, 4, 3, 5])
print(np.sort(x))

[1 2 3 4 5]


- Similarly to the sort method of Python lists, you can also sort an array in-place using the array sort method:

In [10]:
x.sort()
print(x)

[1 2 3 4 5]


- A related function is `argsort`, which instead returns the indices of the sorted elements:

In [11]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)

print(i)

print(x[i])

[1 0 3 2 4]
[1 2 3 4 5]


### Sorting Along Rows or Columns

- A useful feature of NumPy’s sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the axis argument. For example:

In [17]:
rng = np.random.default_rng(seed = 42)
X = rng.integers(0, 10, (4,6))
print(x)

[[0 7 6 4 4 8]
 [0 6 2 0 5 9]
 [7 7 7 7 5 1]
 [8 4 5 3 1 9]]


In [ ]:
# Sort each column of X
print(np.sort(X, axis = 0))

# Sort each row of X
print(np.sort(X, axis = 1))

[[0 4 2 0 1 1]
 [0 6 5 3 4 8]
 [7 7 6 4 5 9]
 [8 7 7 7 5 9]]
[[0 4 4 6 7 8]
 [0 0 2 5 6 9]
 [1 5 7 7 7 7]
 [1 3 4 5 8 9]]


### Partial Sorts: Partitioning

- Sometimes we’re not interested in sorting the entire array, but simply want to find the  k smallest values in the array. NumPy enables this with the np.partition function.  np.partition takes an array and a number k; the result is a new array with the smallest k values to the left of the partition and the remaining values to the right.
- Notice that the first three values in the resulting array are the three smallest in the array, and the remaining array positions contain the remaining values. Within the two partitions, the elements have arbitrary order.

In [26]:
x = np.array([7, 9, 2, 3, 1, 6, 13, 11, 5, 4])
np.partition(x, 3)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 11, 13])

- Similarly to sorting, we can partition along an arbitrary axis of a multidimensional array:

In [28]:
np.partition(X, 2, axis=1)

array([[0, 4, 4, 6, 7, 8],
       [0, 0, 2, 5, 6, 9],
       [1, 5, 7, 7, 7, 7],
       [1, 3, 4, 5, 8, 9]])