## Chapter 10 - Fancy Indexing

In [1]:
import numpy as np
rng = np.random.default_rng(seed = 1701)

### Exploring Fancy Indexing

- Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once. For example, consider the following array:

In [4]:
x = rng.integers(100, size = 10)

ind = [3, 7, 4]
print(x[ind])

[36 96  1]


- When using arrays of indices, the shape of the result reflects the shape of the index  arrays rather than the shape of the array being indexed:

In [6]:
ind = np.array([[3,7],
                [4, 5]])
print(x[ind])

[[36 96]
 [ 1  6]]


- Fancy indexing also works in multiple dimensions. Consider the following array:

In [10]:
x = np.arange(12).reshape(3,4)

row = np.array([0, 1, 2])
col = np.array([2, 1, 3])

print(x[row, col])

[ 2  5 11]


- The pairing of indices in fancy indexing follows all the broadcasting rules. So, for example, if we combine a column vector and a row vector within the indices, we get a two-dimensional result:

In [12]:
print(x[row[:, np.newaxis], col])

[[ 2  1  3]
 [ 6  5  7]
 [10  9 11]]


### Combined Indexing

- Fancy indexing can be combined with the other indexing schemes we’ve seen.

In [13]:
print(x)

# Fancy indexing with simple indices
print(x[2, [2, 0, 1]])

# Fancy indexing with slicing
print(x[1:, [2, 0, 1]])

# Fancy indexing with masking
mask = np.array([True, False, True, False])
print(x[row[:, np.newaxis], mask])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[10  8  9]
[[ 6  4  5]
 [10  8  9]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


### Modifying Values with Fancy Indexing

- Just as fancy indexing can be used to access parts of an array, it can also be used to modify parts of an array.

In [16]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])

print(x)

# Assigning a value to multiple indices via fancy indexing
x[i] = 99

# Using assignment-type operator
x[i] -= 10
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0 89 89  3 89  5  6  7 89  9]
