## Chapter 4 - Understanding Data Types in Python

In [2]:
import numpy as np

### Creating Arrays from Python Lists

In [3]:
# Integer Array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

- NumPy arrays can only contain data of the same type. If the types do not match, NumPy will upcast them according to its type promotion rules.

In [4]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

- If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [5]:
np.array([1, 2, 3, 4], dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

- Finally, unlike Python lists, which are always one-dimensional sequences, NumPy arrays can be multidimensional. Here’s one way of initializing a multidimensional array using a list of lists:

In [6]:
# Nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [7]:
# Create a length-10 integer array filled with 0s
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# Create a 3x3 array of uniformly distributed
# pseudorandom values between 0 and 1
np.random.random((3, 3))

array([[0.02536684, 0.77869826, 0.00705338],
       [0.46017971, 0.36145966, 0.61403733],
       [0.19800974, 0.25302707, 0.26615784]])

In [13]:
# Create a 3x3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.51946353, -0.72921538, -0.60103968],
       [ 0.91804407, -0.17050341, -0.40186888],
       [-0.97896452,  1.39170225, -0.75607941]])

In [14]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 0, 4],
       [0, 2, 5],
       [6, 3, 4]])

In [16]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Create an uninitialized array of three integers; the values will be
# whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])