### Chapter 6 - Computation on NumPy Arrays: Universal Functions

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)

### Exploring NumPy’s Ufuncs

`Ufuncs` exist in two flavors: *unary* ufuncs, which operate on a single input, and *binary*  ufuncs, which operate on two inputs. We’ll see examples of both these types of functions here.

#### Array Arithmetic

- The standard addition, subtraction, multiplication, and division can all be used. There is also a unary ufunc for negation, a ** operator for exponentiation, and a % operator for modulus:

In [ ]:
x = np.arange(4)

print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In addition, these can be strung together however you wish, and the standard order of operations is respected:

In [4]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

#### Absolute Value

- Just as NumPy understands Python’s built-in arithmetic operators, it also understands Python’s built-in absolute value function:

In [5]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

The corresponding NumPy ufunc is `np.absolute`, which is also available under the alias `np.abs`:

In [6]:
np.absolute(x)

array([2, 1, 0, 1, 2])

This ufunc can also handle complex data, in which case it returns the magnitude:

In [7]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

#### Trigonometric Functions

In [9]:
theta = np.linspace(0, np.pi, 3)

print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [10]:
x = [-1, 0, 1]

print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


- **IMPORTANT:** The values are computed to within machine precision, which is why values that should be zero do not always hit exactly zero.

#### Exponents and Logarithms

In [11]:
x = [1, 2, 3]

print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3., x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3.  9. 27.]


In [12]:
x = [1, 2, 4, 10]

print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


- There are also some specialized versions that are useful for maintaining precision with very small input; When x is very small, these functions give more precise values than if the raw `np.log` or `np.exp` were to be used:

In [13]:
x = [0, 0.001, 0.01, 0.1]

print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


#### Specialized Ufuncs

- Another excellent source for more specialized ufuncs is the submodule `scipy.special`. If you want to compute some obscure mathematical function on your data,  chances are it is implemented in `scipy.special`. There are far too many functions to list them all, but the following snippet shows a couple that might come up in a statistics context:

In [14]:
from scipy import special

# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10] 

print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


### Advanced Ufunc Features

#### Specifying Output

- For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. For all ufuncs, this can be done using the `out` argument of the function:

In [15]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
print(y)

[ 0. 10. 20. 30. 40.]


- This can even be used with array views. For example, we can write the results of a computation to every other element of a specified array:

In [16]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


- **IMPORTANT:** If we had instead written `y[::2] = 2 ** x`, this would have resulted in the creation of a temporary array to hold the results of `2 ** x`, followed by a second operation copying those values into the y array. This doesn’t make much of a difference for such a small computation, but for very large arrays the memory savings from careful use of the out argument can be significant.

#### Aggregations

- For binary ufuncs, aggregations can be computed directly from the object. For example, if we’d like to reduce an array with a particular operation, we can use the `reduce` method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains. 

- For example, calling reduce on the add ufunc returns the sum of all elements in the array:

In [19]:
x = np.arange(1, 6)
print(np.add.reduce(x))

15


- Similarly, calling `reduce` on the `multiply` ufunc results in the product of all array elements:

In [21]:
print(np.multiply.reduce(x))

120


- If we’d like to store all the intermediate results of the computation, we can instead use  `accumulate`:

In [23]:
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[ 1  3  6 10 15]
[  1   2   6  24 120]


#### Outer Products

Finally, any ufunc can compute the output of all pairs of two different inputs using the outer method. This allows you, in one line, to do things like create a multiplication table:

In [25]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])