## Chapter 5 - The Basics of NumPy Arrays

In [8]:
import numpy as np
rng = np.random.default_rng(seed = 1701)

In [9]:
x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3, 4)) # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three-dimensional array

### NumPy Array Attributes

- Each array has attributes including `ndim` (the number of dimensions), `shape` (the size of each dimension), `size` (the total size of the array), and `dtype` (the type of each element):

In [10]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype: ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:  int64


### Array Indexing: Accessing Single Elements

- If you are familiar with Python’s standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the ith value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [21]:
print(x1)
print(x2)

[9 4 0 3 8 6]
[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]


In [ ]:
print(x1[0], x1[4], x1[-1])
print(x2[0, 0], x2[2 , -1])

9 8 6
3 9


- Values can also be modified using any of the preceding index notation:

In [24]:
x2[0, 0] = 12
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


- **IMPORTANT:** Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value into an integer array, the value will be silently truncated. Don’t be caught unaware by this behavior!

### Array Slicing: Accessing Subarrays

- Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon `:` character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this: `x[start:stop:step]`
    - If any of these are unspecified, they default to the values `start=0`, `stop=<size of  dimension>`, `step=1`.

#### One-Dimensional Subarrays

In [25]:
print(x1)

# First three elements
print(x1[:3]) 

# Elements after index 3
print(x1[3:])

# Middle subarray
print(x1[1:4])

# Every second element
print(x1[::2])

# Every second element, starting at index 1
print(x1[1::2])

[9 4 0 3 8 6]
[9 4 0]
[3 8 6]
[4 0 3]
[9 0 8]
[4 3 6]


- A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [26]:
x1[::-1] # all elements, reversed

array([6, 8, 3, 0, 4, 9])

In [27]:
x1[4::-2] # every second element from index 4, reversed

array([8, 0, 9])

#### Multidimensional Subarrays

- Multidimensional slices work in the same way, with multiple slices separated by commas. For example:

In [30]:
print(x2)

# first two rows & three columns
print(x2[:2, :3])

# three rows, every second column
print(x2[:3, ::2])

# all rows & columns, reversed
print(x2[::-1, ::-1])

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]
[[12  1  3]
 [ 4  0  2]]
[[12  3]
 [ 4  2]
 [ 0  6]]
[[ 9  6  0  0]
 [ 3  2  0  4]
 [ 7  3  1 12]]


- One commonly needed routine is accessing single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon `:`:

In [34]:
# first column of x2
print(x2[:, 0])

# fisrt row of x2
print(x2[0, :])

[12  4  0]
[12  1  3  7]


- In the case of row access, the empty slice can be omitted for a more compact syntax:

In [35]:
x2[0] # equivalent to x2[0, :] 

array([12,  1,  3,  7])

#### Subarrays as No-Copy Views

- **IMPORTANT:** Unlike Python list slices, NumPy array slices are returned as views rather than copies of the array data. Consider our two-dimensional array from before:

In [38]:
print(x2)

x2_sub = x2[:2, :2]
print(x2_sub)

x2_sub[0, 0] = 99
print(x2_sub)

print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]
[[12  1]
 [ 4  0]]
[[99  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


#### Creating Copies of Arrays

- Despite the features of array views, it’s sometimes useful to instead explicitly copy the data within an array or a subarray. This is easiest to do with the copy method:

In [40]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

print(x2)

[[99  1]
 [ 4  0]]
[[42  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


### Reshaping of Arrays

- Another useful type of operation is reshaping of arrays, which can be done with the  reshape method. For example, if you want to put the numbers 1 through 9 in a 3 × 3  grid, you can do the following:

In [42]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- Note that for this to work, the size of the initial array must match the size of the reshaped array, and in most cases the reshape method will return a no-copy view of the initial array.

- A common reshaping operation is converting a one-dimensional array into a twodimensional row or column matrix:

In [45]:
x = np.array([1, 2, 3])

# row vector via reshape
print(x.reshape((1, 3)))

# column vector via reshape
print(x.reshape(3, 1))

[[1 2 3]]
[[1]
 [2]
 [3]]


A convenient shorthand for this is to use `np.newaxis` in the slicing syntax:

In [48]:
# row vector via newaxis
print(x[np.newaxis, :])

# column vector via newaxis
print(x[:, np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]


### Array Concatenation and Splitting

#### Concatenation of Arrays

- Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines `np.concatenate`, `np.vstack`, and `np.hstack`. `np.concatenate` takes a tuple or list of arrays as its first argument, as you can see here:

In [49]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

- You can also concatenate more than two arrays at once:

In [50]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


- And it can be used for two-dimensional arrays:

In [51]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the first axis
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- For working with arrays of mixed dimensions, it can be clearer to use the `np.vstack` (vertical stack) and `np.hstack` (horizontal stack) functions:

In [56]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
# horizontally stack the arrays
y = np.array([[99],  [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

- Similarly, for higher-dimensional arrays, `np.dstack` will stack arrays along the third axis.

#### Splitting of Array

- The opposite of concatenation is splitting, which is implemented by the functions  `np.split`, `np.hsplit`, and `np.vsplit`. For each of these, we can pass a list of indices  giving the split points:

In [59]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that $N$ split points leads to $N + 1$ subarrays. The related functions `np.hsplit` and `np.vsplit` are similar:

In [61]:
grid = np.arange(16).reshape((4, 4))
print(grid)

upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


- Similarly, for higher-dimensional arrays, np.dsplit will split arrays along the third axis.