## Chapter 7 - Aggregations: min, max, and  Everything in Between

In [12]:
import numpy as np
rng = np.random.default_rng()

### Summing the Values in an Array

In [13]:
L = rng.random(100)

print(sum(L))
print(np.sum(L))

46.944808433355824
46.94480843335581


- **IMPORTANT:** the `sum` function and the `np.sum` function are not identical, which can sometimes lead to confusion! In particular, their optional arguments have different meanings (`sum(x, 1)` initializes the sum at 1, while `np.sum(x, 1)` sums along axis 1), and `np.sum` is aware of multiple array dimensions.

### Minimun and Maximum

In [14]:
big_array = rng.random(1000000)

print(min(big_array), max(big_array))
print(np.min(big_array), np.max(big_array))
print(big_array.min(), big_array.max(), big_array.sum())

6.127796455812629e-07 0.9999988048785801
6.127796455812629e-07 0.9999988048785801
6.127796455812629e-07 0.9999988048785801 499896.77466724784


### Multidimensional Aggregates

In [16]:
M = rng.integers(0, 10, (3, 4))
print(M)

print(M.sum())

# Aggregation on columns
print(M.sum(axis = 0))

# Aggregation on rows
print(M.sum(axis = 1))

[[5 1 0 2]
 [5 6 0 6]
 [6 5 5 1]]
42
[16 12  5  9]
[ 8 17 17]


- **IMPORTANT:** The way the axis is specified here can be confusing to users coming from other languages. The `axis` keyword specifies the dimension of the array that will be collapsed, rather than the dimension that will be returned. So, specifying `axis=0` means that axis 0 will be collapsed: for two-dimensional arrays, values within each column will be aggregated.