## Chapter 8 - Computation on Arrays: Broadcasting

In [1]:
import numpy as np

### Introducing Broadcasting

- Binary operations are performed on an element-by-element basis. Broadcasting allows these types of binary operations to be performed on arrays of different sizes—for example, we can just as easily add a scalar (think of it as a zerodimensional array) to an array:

In [3]:
a = np.array([0, 1, 2])

print(a + 5)

[5 6 7]


- We can think of this as an operation that stretches or duplicates the value 5 into the array [5, 5, 5], and adds the results. We can similarly extend this idea to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array:

In [5]:
M = np.ones((3, 3))
print(M + a)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


- More complicated cases can involve broadcasting of both arrays. Consider the following example:

In [9]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

print(a + b)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


### Rules of Broadcasting

- **Rule 1:** If the two arrays differ in their number of dimensions, the shape of the one with  fewer dimensions is padded with ones on its leading (left) side.
- **Rule 2:** If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- **Rule 3:** If in any dimension the sizes disagree and neither is equal to 1, an error is raised.